apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: luisandia-com-tls
spec:
  secretName: luisandia-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: luisandia.com
  dnsNames:
  - luisandia.com
  - www.luisandia.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - luisandia.com
      - www.luisandia.com