apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: luisandia-tls
spec:
    secretName: luisandia-com
    isserRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: luisandia.com
    dnsNames:
        - luisandia.com
        - www.luisandia.com
    acme:
        config:
            - http01:
                ingressClass:nginx
              domains:
                - luisandia.com
                - www.luisandia.com